services:
  - type: web
    name: hk-speaks-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: STORAGE_PUBLIC_URL_BASE
        value: /v1/storage
      - key: HOST
        value: 0.0.0.0

